import 'package:get/get.dart';

class Message extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        "en": {
          "welcome": "welcome",
          "please, enter your data carefully":
              "please, enter your data carefully",
          "first name": "first name",
          "last name": "last name",
          "gender": "gender",
          "male": "male",
          "female": "female",
          "date of birth": "date of birth",
          "username": "username",
          "phone number": "phone number",
          "email": "email",
          "password": "password",
          "confirm password": "confirm password",
          "sign up": "sign up",
          "sign up?": "sign up?",
          "sign in": "sign in",
          "sign in?": "sign in?",
          "sign out": "sign out",
          "change language": "change language",
          "account settings": "account settings",
          "signing in completed successfully":
              "signing in completed successfully",
          "forgot password?": "forgort password?",
          "your account is created successfuly, sign in now":
              "your account is created successfuly, sign in now",
          "passwords are not matching": "passwords are not matching",
          "Vision Tests": "Vision Tests",
          "test your vision with us now": "test your vision with us now",
          "Optometrists": "Optometrists",
          "find near optometrists and book\nan appointment":
              "find near optometrists and book\nan appointment",
          "go": "go",
          "order now": "order now",
          "orders": "orders",
          "in-process": "in-process",
          "delivered": "delivered",
          "me": "me",
          "diagnoses": "diagnoses",
          "wish list": "wish list",
          "products": "products",
          "start test": "start test",
          "details": "details",
          "remove": "remove",
          "description": "description",
          "add to cart": "add to cart",
          "try it now": "try it now",
          "appointments": "appointments",
          "account": "account",
          "cart": "cart",
          "services": "services",
          "categories": "categories"
        },
        "ar": {
          "welcome": "أهلا بك",
          "please, enter your data carefully": "من فضلك, أدخل بياناتك بحذر",
          "first name": "الاسم الأول",
          "last name": "الاسم الأخير",
          "gender": "الجنس",
          "male": "ذكر",
          "female": "أنثى",
          "date of birth": "تاريخ الميلاد",
          "username": "اسم المستخدم",
          "phone number": "رقم الهاتف",
          "email": "البريد الالكتروني",
          "password": "كلمة السر",
          "confirm password": "نأكيد كلمة السر",
          "sign up": "انشاء حساب",
          "sign up?": "انشاء حساب؟",
          "forgot password?": "نسيت كلمة السر؟",
          "sign in": "تسجيل الدخول",
          "sign in?": "تسجيل الدخول؟",
          "sign out": "تسجيل الخروج",
          "change language": "تغيير اللغة",
          "account settings": "اعدادات الحساب",
          "signing in completed successfully": "تم تسجيل الدخول بنجاح",
          "your account is created successfuly, sign in now":
              "تم انشاء حسابك بنجاح, سجل دخولك الان",
          "passwords are not matching": "كلمات السر لا تتطابق",
          "Vision Tests": "اختبارات النظر",
          "test your vision with us now": "اختبر نظرك معنا الان",
          "Optometrists": "أخصائيو العيون",
          "find near optometrists and book\nan appointment":
              "ابحث عن أخصائيو العيون الأقرب إليك\n واحجز موعد",
          "go": "اذهب",
          "order now": "اطلب الان",
          "orders": "الطلبات",
          "in-process": "قيد المعالجة",
          "delivered": "تم التوصيل",
          "me": "أنا",
          "diagnoses": "التشخيصات",
          "wish list": "المفضلات",
          "products": "المنتجات",
          "start test": "ابدأ الاختبار",
          "details": "تفاصيل",
          "remove": "إزالة",
          "description": "الوصف",
          "add to cart": "إضافة الى السلة",
          "try it now": "جربها الان",
          "appointments": "المواعيد",
          "account": "الحساب",
          "cart": "السلة",
          "services": "الخدمات",
          "categories": "التصنيفات"
        }
      };
}
